title=KFSM-VIZ-PLUGIN
date=2020-02-28
type=project
status=published
summary=KFSM - Visualization Gradle plugin
~~~~~~
= KFSM Visualization Gradle plugin

The Gradle plugin provided for parsing configured files containing the DSL in order to construct a model of the FSM for visual
representation.
This model includes the content of the lambdas used in guards and actions.


== Getting Started

Plugin Id: io.jumpco.open.kfsm.viz-plugin
Version: 1.0.8

=== Gradle Groovy DSL
[source,groovy]
----
plugins {
    id 'io.jumpco.open.kfsm.viz-plugin' version '1.0.8'
}
----

== Configuration

=== Gradle Groovy DSL
[source,groovy]
----
kfsmViz {
  fsm('PacketReaderFSM') {
    input = file('src/main/kotlin/PacketReader.kt') // <1>
    isGeneratePlantUml = true // <2>
    isGenerateAsciidoc = true // <3>
    output = 'packet-reader' // <4>
    outputFolder = file('generated') // <5>
    plantUmlName = 'packet-reader-statediagram.plantuml' // <6>
    asciidocName = 'packet-reader-state-table.adoc'      // <7>
  }
}
----
<1> `input: File`: Required, fully qualified filename of relevant source file
<2> `isGeneratePlantUml: Boolean`: Required default is false
<3> `isGenerateAsciidoc: Boolean`: Required default is false
<4> `output: String`: Optional filename base. The default is the classname
<5> `outputFolder: File`: Optional directory for output file. Default is `$buildDir/generated`
<6> `plantUmlName: String`: Optional filename for plantuml output. Default is `$output.plantuml`
<7> `asciidocName: String`: Optional name of Asciidoc output file. Default is `$output.adoc`

== Resources

* link:https://github.com/open-jumpco/kfsm-viz-plugin[Source]
